#pragma once
#include <vector>

namespace pareto_nbd {

// Randomized PIT for count forecasts (Czado, Gneiting & Held 2009),
// mirroring score.randomized_pit exactly except that the tie-breaking
// uniform draws are passed in as `tie_break` (one per customer) instead
// of generated from an RNG internally — this makes the function pure and
// exactly golden-file testable; a caller generates `tie_break` itself
// (e.g. via std::uniform_real_distribution) before calling this.
// pred: (J x N) predictive draws. y: (N,) truths. tie_break: (N,) in [0,1).
std::vector<double> randomized_pit(const std::vector<std::vector<double>>& pred,
                                    const std::vector<double>& y,
                                    const std::vector<double>& tie_break);

// Deterministic core of conformal.recalibrate_samples: given calibration
// PITs `u` (N_cal values, from randomized_pit), output-quantile draws `p`
// (n_out values in [0,1), already generated by the caller), and the raw
// test-set predictive samples `pred_test` (J x N_test, NOT pre-sorted —
// this function sorts internally, matching
// np.sort(pred_test, axis=0) in the Python original), returns the (n_out x
// N_test) recalibrated predictive. Uses the same linear-interpolation
// quantile method as numpy's default (see cohort_features.cpp's
// quantile_linear for the same formula applied elsewhere in this project).
std::vector<std::vector<double>> apply_conformal_warp(
    const std::vector<double>& u, const std::vector<double>& p,
    const std::vector<std::vector<double>>& pred_test);

}  // namespace pareto_nbd
